version: '3'

services:
  scanner:
    build: .
    image: ghcr.io/drakeapps/brother-scanner
    network_mode: host
    environment:
      - NAME=SCANNER
      - MODEL=MFC-L2710DW
      - IPADDRESS=192.168.1.31
    volumes:
      - ./scans:/scans
      - ./script:/opt/brother/scanner/brscan-skey/script/

